In [ ]:
pip install pandas

hello

In [2]:
import pandas as pd
data={'name':['Tom','Jerry','Mickey','Donald'],
      'age':[20,21,19,18],}
df=pd.DataFrame(data)

ModuleNotFoundError: No module named 'pandas'

In [5]:
pip uninstall pandas -y

Found existing installation: pandas 3.0.3
Uninstalling pandas-3.0.3:
  Successfully uninstalled pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [6]:
pip uninstall pandas -y

Note: you may need to restart the kernel to use updated packages.

WARNING: Skipping pandas as it is not installed.

In [7]:
pip cache purge

Files removed: 6 (1.9 MB)
Directories removed: 0
Note: you may need to restart the kernel to use updated packages.

In [8]:
pip install pandas==2.2.3

Collecting pandas==2.2.3
  Downloading pandas-2.2.3.tar.gz (4.4 MB)
     ---------------------------------------- 0.0/4.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/4.4 MB ? eta -:--:--
     -- ------------------------------------- 0.3/4.4 MB ? eta -:--:--
     ----------------------------------- ---- 3.9/4.4 MB 18.9 MB/s eta 0:00:01
     -------------------------------------- - 4.2/4.4 MB 9.9 MB/s eta 0:00:01
     ---------------------------------------- 4.4/4.4 MB 8.0 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
Note: you may need to restart the kernel to use updated packages.

  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      Traceback (most recent call last):
        File "c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 178, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 1048, in wrapper
          return func(*args, **kwargs)
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 1112, in build_wheel
          with _project(config_settings) as project:
               ~~~~~~~~^^^^^^^^^^^^^^^^^
        File "C:\Users\Latitude\AppData\Local\Python\pythoncore-3.14-64\Lib\contextlib.py", line 141, in __enter__
          return next(self.gen)
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 986, in _project
          with Project.with_temp_working_dir(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                  build_dir=settings.get('builddir'),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  meson_args=typing.cast(MesonArgs, meson_args),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                  editable_verbose=bool(settings.get('editable-verbose'))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ) as project:
          ^
        File "C:\Users\Latitude\AppData\Local\Python\pythoncore-3.14-64\Lib\contextlib.py", line 141, in __enter__
          return next(self.gen)
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 831, in with_temp_working_dir
          yield cls(source_dir, tmpdir, build_dir, meson_args, editable_verbose)
                ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 652, in __init__
          _check_meson_version()
          ~~~~~~~~~~~~~~~~~~~~^^
        File "C:\Users\Latitude\AppData\Local\Temp\pip-build-env-jogbyzmx\overlay\Lib\site-packages\mesonpy\__init__.py", line 1027, in _check_meson_version
          meson_version = subprocess.run(['meson', '--version'], check=False, text=True, capture_output=True).stdout
                          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Latitude\AppData\Local\Python\pythoncore-3.14-64\Lib\subprocess.py", line 555, in run
          with Popen(*popenargs, **kwargs) as process:
               ~~~~~^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Latitude\AppData\Local\Python\pythoncore-3.14-64\Lib\subprocess.py", line 1039, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
          ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              pass_fds, cwd, env,
                              ^^^^^^^^^^^^^^^^^^^
          ...<5 lines>...
                              gid, gids, uid, umask,
                              ^^^^^^^^^^^^^^^^^^^^^^
                              start_new_session, process_group)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Latitude\AppData\Local\Python\pythoncore-3.14-64\Lib\subprocess.py", line 1553, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                                   # no special security
                                   ^^^^^^^^^^^^^^^^^^^^^
          ...<4 lines>...
                                   cwd,
                                   ^^^^
                                   startupinfo)
                                   ^^^^^^^^^^^^
      OSError: [WinError 4551] An Application Control policy has blocked this file
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> pandas

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

In [1]:
pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ----------- ---------------------------- 2.9/9.9 MB 18.7 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.9 MB 11.4 MB/s eta 0:00:01
   ------------------------ --------------- 6.0/9.9 MB 9.4 MB/s eta 0:00:01
   ---------------------------- ----------- 7.1/9.9 MB 8.1 MB/s eta 0:00:01
   -------------------------------- ------- 8.1/9.9 MB 7.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 6.5 MB/s  0:00:01
Installing collected packages: pandas
Successfully installed pandas-3.0.3
Note: you may need to restart the kernel to use updated packages.

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\Latitude\Desktop\project3\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd
print(pd.__version__)

:

In [ ]:
print("hello")

hello

step1:- Import Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

Step 2:- Load the Dataset

In [4]:
df=pd.read_csv(r"C:\Users\Latitude\Desktop\project3\Dataset\Raw\retail_store_inventory.csv")

Display the first five rows

In [5]:
df.head(5)

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price
0,01-01-2022,S001,P0001,Groceries,North,231,127,55,135.47,33.50
1,01-01-2022,S001,P0002,Toys,South,204,150,66,144.04,63.01
2,01-01-2022,S001,P0003,Toys,West,102,65,51,74.02,27.99
3,01-01-2022,S001,P0004,Toys,North,469,61,164,62.18,32.72
4,01-01-2022,S001,P0005,Electronics,East,166,14,135,9.26,73.64

Step 4:- Check dataset Shape

In [6]:
df.shape

(73100, 10)

Check Coloumn Name

In [7]:
df.columns

Index(['Date', 'Store ID', 'Product ID', 'Category', 'Region',
       'Inventory Level', 'Units Sold', 'Units Ordered', 'Demand Forecast',
       'Price'],
      dtype='str')

Step6 :- Dataset Information

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             73100 non-null  str
 1   Store ID         73100 non-null  str
 2   Product ID       73100 non-null  str
 3   Category         73100 non-null  str
 4   Region           73100 non-null  str
 5   Inventory Level  73100 non-null  int64
 6   Units Sold       73100 non-null  int64
 7   Units Ordered    73100 non-null  int64
 8   Demand Forecast  73100 non-null  float64
 9   Price            73100 non-null  float64
dtypes: float64(2), int64(3), str(5)
memory usage: 5.6 MB

Summary Statistics

In [9]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108
std,129.949514,108.919406,52.277448,109.254076,26.021945
min,50.000000,0.000000,20.000000,-9.990000,10.000000
25%,162.000000,49.000000,65.000000,53.670000,32.650000
50%,273.000000,107.000000,110.000000,113.015000,55.050000
75%,387.000000,203.000000,155.000000,208.052500,77.860000
max,500.000000,499.000000,200.000000,518.550000,100.000000

Step8:-Check Missing Values

In [10]:
df.isnull().sum()

Date               0
Store ID           0
Product ID         0
Category           0
Region             0
Inventory Level    0
Units Sold         0
Units Ordered      0
Demand Forecast    0
Price              0
dtype: int64