Step 1 :- Importing the required libraries

In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Step 2 :- Loading the cleaned data set

In [6]:
df = pd.read_csv("C:/Users/Latitude/Desktop/project3/Dataset/Processed/cleaned_data.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Year,Month,Month_name,Day,Day_Name
0,2022-01-01,S001,P0001,Groceries,North,231,127,55,135.47,33.50,2022,1,January,1,Saturday
1,2022-01-01,S001,P0002,Toys,South,204,150,66,144.04,63.01,2022,1,January,1,Saturday
2,2022-01-01,S001,P0003,Toys,West,102,65,51,74.02,27.99,2022,1,January,1,Saturday
3,2022-01-01,S001,P0004,Toys,North,469,61,164,62.18,32.72,2022,1,January,1,Saturday
4,2022-01-01,S001,P0005,Electronics,East,166,14,135,9.26,73.64,2022,1,January,1,Saturday

In [8]:
df.shape
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73100 entries, 0 to 73099
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             73100 non-null  str
 1   Store ID         73100 non-null  str
 2   Product ID       73100 non-null  str
 3   Category         73100 non-null  str
 4   Region           73100 non-null  str
 5   Inventory Level  73100 non-null  int64
 6   Units Sold       73100 non-null  int64
 7   Units Ordered    73100 non-null  int64
 8   Demand Forecast  73100 non-null  float64
 9   Price            73100 non-null  float64
 10  Year             73100 non-null  int64
 11  Month            73100 non-null  int64
 12  Month_name       73100 non-null  str
 13  Day              73100 non-null  int64
 14  Day_Name         73100 non-null  str
dtypes: float64(2), int64(6), str(7)
memory usage: 8.4 MB

Step3 :- Summary statistics

In [9]:
df.describe()

,Inventory Level,Units Sold,Units Ordered,Demand Forecast,Price,Year,Month,Day
count,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000,73100.000000
mean,274.469877,136.464870,110.004473,141.494720,55.135108,2022.502052,6.518468,15.700410
std,129.949514,108.919406,52.277448,109.254076,26.021945,0.502728,3.451564,8.807111
min,50.000000,0.000000,20.000000,-9.990000,10.000000,2022.000000,1.000000,1.000000
25%,162.000000,49.000000,65.000000,53.670000,32.650000,2022.000000,4.000000,8.000000
50%,273.000000,107.000000,110.000000,113.015000,55.050000,2023.000000,7.000000,16.000000
75%,387.000000,203.000000,155.000000,208.052500,77.860000,2023.000000,10.000000,23.000000
max,500.000000,499.000000,200.000000,518.550000,100.000000,2024.000000,12.000000,31.000000

Step4:- Checking missing values

In [10]:
df.isnull().sum()

Date               0
Store ID           0
Product ID         0
Category           0
Region             0
Inventory Level    0
Units Sold         0
Units Ordered      0
Demand Forecast    0
Price              0
Year               0
Month              0
Month_name         0
Day                0
Day_Name           0
dtype: int64

Step5:- Checking Duplicate Records

In [11]:
df.duplicated().sum()

np.int64(0)

Step 6:-Checking Unique Categories

In [12]:
df["Category"].unique()

<StringArray>
['Groceries', 'Toys', 'Electronics', 'Furniture', 'Clothing']
Length: 5, dtype: str

Step7:- Counting Records in each catregory

In [13]:
df["Category"].value_counts()

Category
Furniture      14699
Toys           14643
Clothing       14626
Groceries      14611
Electronics    14521
Name: count, dtype: int64

Step8 :- Counting Stores

In [14]:
df["Store ID"].nunique()

5